### PR TITLE
Use conda on macOS

### LINKED ISSUE #103: pip install fails due to conflicts
I verified this with a clean new docker image and a local venv. 

`
INFO: pip is still looking at multiple versions of azureml-dataprep to determine which version is compatible with other requirements. This could take a while.
  Using cached azureml_dataprep-4.14.0-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.10-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.9-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.8-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.7-py3-none-any.whl.metadata (2.1 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached azureml_dataprep-4.12.6-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.5-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.4-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.2-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.1-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.0-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.7-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.6-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.5-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.4-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.3-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.2-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.1-py3-none-any.whl.metadata (2.1 kB)
ERROR: Cannot install azureml-dataprep because these package versions have conflicting dependencies.

The conflict is caused by:
    azureml-dataprep 5.1.6 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.5 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.4 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.3 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.2 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.1 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.0 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.0.0 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 4.14.0 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.10 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.9 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.8 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.7 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.6 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.5 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.4 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.2 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.1 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.0 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.7 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.6 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.5 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.4 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.3 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.2 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.1 depends on dotnetcore2<4.0.0 and >=3.0.0
`

pip --version
pip 24.0 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)

### PR DESCRIPTION
**Pull request by soderlind**
This pull request updates the macOS setup to use conda for managing dependencies. This change improves the consistency and reliability of the development environment across different macOS versions.

Fix #103

### CODE REVIEW

**Comment by soderlind** [comment]
@microsoft-github-policy-service agree

**Comment by luigiw** [comment]
Thank you for this @soderlind! Can you pull from main branch to resolve conflicts?

**Comment by soderlind** [comment]
@luigiw merged

**Review by luigiw — APPROVED** [review]

**Comment by luigiw** [comment]
Thank you, @soderlind.

**Pull request merged**
